# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chiralMS_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chiralMS_settings(object):
    def setupUi(self, chiralMS_settings):
        chiralMS_settings.setObjectName("chiralMS_settings")
        chiralMS_settings.resize(1130, 820)
        self.centralwidget = QtWidgets.QWidget(chiralMS_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.voltage_control_button = QtWidgets.QPushButton(self.centralwidget)
        self.voltage_control_button.setGeometry(QtCore.QRect(40, 600, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.voltage_control_button.setFont(font)
        self.voltage_control_button.setObjectName("voltage_control_button")
        self.motor_control_button = QtWidgets.QPushButton(self.centralwidget)
        self.motor_control_button.setGeometry(QtCore.QRect(40, 660, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.motor_control_button.setFont(font)
        self.motor_control_button.setObjectName("motor_control_button")
        chiralMS_settings.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(chiralMS_settings)
        self.statusbar.setObjectName("statusbar")
        chiralMS_settings.setStatusBar(self.statusbar)

        self.retranslateUi(chiralMS_settings)
        QtCore.QMetaObject.connectSlotsByName(chiralMS_settings)

    def retranslateUi(self, chiralMS_settings):
        _translate = QtCore.QCoreApplication.translate
        chiralMS_settings.setWindowTitle(_translate("chiralMS_settings", "Chiral MS"))
        self.voltage_control_button.setText(_translate("chiralMS_settings", "Voltage control"))
        self.motor_control_button.setText(_translate("chiralMS_settings", "Motor control"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chiralMS_settings = QtWidgets.QMainWindow()
    ui = Ui_chiralMS_settings()
    ui.setupUi(chiralMS_settings)
    chiralMS_settings.show()
    sys.exit(app.exec_())
