# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'electron_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_electron_image_window(object):
    def setupUi(self, electron_image_window):
        electron_image_window.setObjectName("electron_image_window")
        electron_image_window.resize(1150, 890)
        self.electron_image = MplWidget(electron_image_window)
        self.electron_image.setEnabled(False)
        self.electron_image.setGeometry(QtCore.QRect(0, 0, 1151, 891))
        self.electron_image.setObjectName("electron_image")

        self.retranslateUi(electron_image_window)
        QtCore.QMetaObject.connectSlotsByName(electron_image_window)

    def retranslateUi(self, electron_image_window):
        _translate = QtCore.QCoreApplication.translate
        electron_image_window.setWindowTitle(_translate("electron_image_window", "Electron Image"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    electron_image_window = QtWidgets.QWidget()
    ui = Ui_electron_image_window()
    ui.setupUi(electron_image_window)
    electron_image_window.show()
    sys.exit(app.exec_())
