# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'injector_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_injector_settings(object):
    def setupUi(self, injector_settings):
        injector_settings.setObjectName("injector_settings")
        injector_settings.resize(1158, 859)
        self.centralwidget = QtWidgets.QWidget(injector_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        injector_settings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(injector_settings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 21))
        self.menubar.setObjectName("menubar")
        injector_settings.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(injector_settings)
        self.statusbar.setObjectName("statusbar")
        injector_settings.setStatusBar(self.statusbar)

        self.retranslateUi(injector_settings)
        QtCore.QMetaObject.connectSlotsByName(injector_settings)

    def retranslateUi(self, injector_settings):
        _translate = QtCore.QCoreApplication.translate
        injector_settings.setWindowTitle(_translate("injector_settings", "MainWindow"))
        self.pushButton.setText(_translate("injector_settings", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    injector_settings = QtWidgets.QMainWindow()
    ui = Ui_injector_settings()
    ui.setupUi(injector_settings)
    injector_settings.show()
    sys.exit(app.exec_())
