# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mass_spectrum_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zoom_in_mass_spectrum(object):
    def setupUi(self, zoom_in_mass_spectrum):
        zoom_in_mass_spectrum.setObjectName("zoom_in_mass_spectrum")
        zoom_in_mass_spectrum.resize(800, 643)
        self.centralwidget = QtWidgets.QWidget(zoom_in_mass_spectrum)
        self.centralwidget.setObjectName("centralwidget")
        self.mass_spectrum = MplWidget(self.centralwidget)
        self.mass_spectrum.setGeometry(QtCore.QRect(10, 10, 381, 301))
        self.mass_spectrum.setObjectName("mass_spectrum")
        self.electron_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.electron_image.setGeometry(QtCore.QRect(10, 330, 761, 301))
        self.electron_image.setObjectName("electron_image")
        zoom_in_mass_spectrum.setCentralWidget(self.centralwidget)

        self.retranslateUi(zoom_in_mass_spectrum)
        QtCore.QMetaObject.connectSlotsByName(zoom_in_mass_spectrum)

    def retranslateUi(self, zoom_in_mass_spectrum):
        _translate = QtCore.QCoreApplication.translate
        zoom_in_mass_spectrum.setWindowTitle(_translate("zoom_in_mass_spectrum", "mass_spectrum_window"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    zoom_in_mass_spectrum = QtWidgets.QMainWindow()
    ui = Ui_zoom_in_mass_spectrum()
    ui.setupUi(zoom_in_mass_spectrum)
    zoom_in_mass_spectrum.show()
    sys.exit(app.exec_())
