# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_file_hvc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_open_file_hvc(object):
    def setupUi(self, open_file_hvc):
        open_file_hvc.setObjectName("open_file_hvc")
        open_file_hvc.resize(201, 131)
        self.centralwidget = QtWidgets.QWidget(open_file_hvc)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 158, 75))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_file_as_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.open_file_as_label.setFont(font)
        self.open_file_as_label.setAlignment(QtCore.Qt.AlignCenter)
        self.open_file_as_label.setObjectName("open_file_as_label")
        self.verticalLayout.addWidget(self.open_file_as_label)
        self.open_hvc = QtWidgets.QLineEdit(self.layoutWidget)
        self.open_hvc.setObjectName("open_hvc")
        self.verticalLayout.addWidget(self.open_hvc)
        self.open_file = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.open_file.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.open_file.setObjectName("open_file")
        self.verticalLayout.addWidget(self.open_file)
        open_file_hvc.setCentralWidget(self.centralwidget)

        self.retranslateUi(open_file_hvc)
        QtCore.QMetaObject.connectSlotsByName(open_file_hvc)

    def retranslateUi(self, open_file_hvc):
        _translate = QtCore.QCoreApplication.translate
        open_file_hvc.setWindowTitle(_translate("open_file_hvc", "Open "))
        self.open_file_as_label.setText(_translate("open_file_hvc", "Open file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    open_file_hvc = QtWidgets.QMainWindow()
    ui = Ui_open_file_hvc()
    ui.setupUi(open_file_hvc)
    open_file_hvc.show()
    sys.exit(app.exec_())
