# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_file_as_hvc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save_window_hvc(object):
    def setupUi(self, save_window_hvc):
        save_window_hvc.setObjectName("save_window_hvc")
        save_window_hvc.resize(234, 115)
        self.centralwidget = QtWidgets.QWidget(save_window_hvc)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 194, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_file_as_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_file_as_label.setFont(font)
        self.save_file_as_label.setAlignment(QtCore.Qt.AlignCenter)
        self.save_file_as_label.setObjectName("save_file_as_label")
        self.verticalLayout.addWidget(self.save_file_as_label)
        self.save_as_hvc = QtWidgets.QLineEdit(self.layoutWidget)
        self.save_as_hvc.setObjectName("save_as_hvc")
        self.verticalLayout.addWidget(self.save_as_hvc)
        self.save_file_as_hvc = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.save_file_as_hvc.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.save_file_as_hvc.setObjectName("save_file_as_hvc")
        self.verticalLayout.addWidget(self.save_file_as_hvc)
        save_window_hvc.setCentralWidget(self.centralwidget)

        self.retranslateUi(save_window_hvc)
        QtCore.QMetaObject.connectSlotsByName(save_window_hvc)

    def retranslateUi(self, save_window_hvc):
        _translate = QtCore.QCoreApplication.translate
        save_window_hvc.setWindowTitle(_translate("save_window_hvc", "Save"))
        self.save_file_as_label.setText(_translate("save_window_hvc", "Save file as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    save_window_hvc = QtWidgets.QMainWindow()
    ui = Ui_save_window_hvc()
    ui.setupUi(save_window_hvc)
    save_window_hvc.show()
    sys.exit(app.exec_())
