# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warning_window(object):
    def setupUi(self, warning_window):
        warning_window.setObjectName("warning_window")
        warning_window.resize(222, 80)
        self.warning_label = QtWidgets.QLabel(warning_window)
        self.warning_label.setGeometry(QtCore.QRect(10, 20, 201, 21))
        self.warning_label.setAlignment(QtCore.Qt.AlignCenter)
        self.warning_label.setObjectName("warning_label")
        self.ok_button = QtWidgets.QPushButton(warning_window)
        self.ok_button.setGeometry(QtCore.QRect(70, 50, 75, 23))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(warning_window)
        QtCore.QMetaObject.connectSlotsByName(warning_window)

    def retranslateUi(self, warning_window):
        _translate = QtCore.QCoreApplication.translate
        warning_window.setWindowTitle(_translate("warning_window", "Error"))
        self.ok_button.setText(_translate("warning_window", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    warning_window = QtWidgets.QWidget()
    ui = Ui_warning_window()
    ui.setupUi(warning_window)
    warning_window.show()
    sys.exit(app.exec_())
